# Generated by Django 4.0.5 on 2022-07-02 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Double',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('double_value', models.IntegerField(blank=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 7, 2, 13, 54, 33, 238735))),
            ],
        ),
    ]
