# Generated by Django 4.0.5 on 2022-07-02 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_double_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='double',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 2, 14, 21, 23, 221073), null=True),
        ),
    ]
